const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHORIZED = 401;
const STATUS_FORBIDDEN = 403;
const STATUS_NOT_FOUND = 404;
const STATUS_CONFLICT = 409;
const STATUS_SERVER_ERROR = 500;

const ERROR_INVALID_DATA = 'Invalid request data';
const ERROR_UNAUTHORIZED = 'Authorization required';
const ERROR_FORBIDDEN = 'Access denied';
const ERROR_NOT_FOUND = 'Requested resource not found';
const ERROR_CONFLICT = 'Resource conflict';
const ERROR_SERVER = 'An error occurred on the server';
const ERROR_INVALID_CREDENTIALS = 'Incorrect email or password';

module.exports = {
  STATUS_BAD_REQUEST,
  STATUS_UNAUTHORIZED,
  STATUS_FORBIDDEN,
  STATUS_NOT_FOUND,
  STATUS_CONFLICT,
  STATUS_SERVER_ERROR,
  ERROR_INVALID_DATA,
  ERROR_UNAUTHORIZED,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_CONFLICT,
  ERROR_SERVER,
  ERROR_INVALID_CREDENTIALS,
};
